version: '3'

services:
  apache:
    image: httpd:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/ssl/server.crt:/usr/local/apache2/conf/ssl/server.crt
      - ./apache/ssl/server.key:/usr/local/apache2/conf/ssl/server.key
      - ./data/html:/usr/local/apache2/htdocs
      - ./php:/var/www/html
    depends_on:
      - php

  php:
    image: php:7.4-fpm-alpine
    command: ["php-fpm", "-F"]
    volumes:
      - ./data/html:/var/www/html
      - ./data/html:/usr/local/apache2/htdocs
